# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'budget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for budget
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RealmSwift'

  target 'budgetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'budgetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
